### ISSUE TITLE
RSS: Allow visitors to generate a custom feed from post kinds

### ISSUE THREAD

**Issue by peterwilsoncc** [dshanske/indieweb-extras#1]
Allow visitors to generate a custom feed from any combination of post kinds available.

A bookmarks, favourites & likes URL could look something like:
/feed/?kinds=[bookmarks,favorites,likes]

A combined notes & photos
/feed/?kinds=[notes,photos]

**Comment by dshanske** [comment]
A custom RSS/Atom feed or an H-Feed feed?

**Comment by peterwilsoncc** [comment]
I was thinking as a custom RSS, but you're prompt reminded me that WP has it built in.

These URLs show posts in either the notes quick-notes categories:
https://peterwilson.cc/category/notes,quick-notes/
https://peterwilson.cc/category/notes,quick-notes/feed/

So closing this as invalid.
